name: flutter_getx_template
description: Boilarplate template of Flutter GetX.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: "3.13.0"

dependencies:
  flutter:
    sdk: flutter
  animations: 2.0.8
  cached_network_image: 3.3.0
  cupertino_icons: 1.0.6
  dio: 5.3.3
  font_awesome_flutter: 10.6.0
  flutter_localizations:
    sdk: flutter
  fluttertoast: 8.2.2
  flutter_svg: 2.0.8
  get: 4.6.6
  intl: 0.18.1
  logger: 2.0.2+1
  pretty_dio_logger: 1.3.1
  shared_preferences: 2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.2
  analyzer: 5.13.0
  dart_code_metrics: any
  change_app_package_name: 1.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 200
        - asset: fonts/Roboto-Light.ttf
          weight: 200
        - asset: fonts/Roboto-Regular.ttf
          weight: 200
        - asset: fonts/Roboto-Medium.ttf
          weight: 300
        - asset: fonts/Roboto-Bold.ttf
          weight: 600
        - asset: fonts/Roboto-Italic.ttf
          style: italic
